// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QInfoRanker.Infrastructure.Data;

#nullable disable

namespace QInfoRanker.Infrastructure.Migrations
{
    [DbContext(typeof(QInfoRankerDbContext))]
    partial class QInfoRankerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("QInfoRanker.Core.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("FinalScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("LlmScore")
                        .HasColumnType("REAL");

                    b.Property<int?>("NativeScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinalScore");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("SourceId");

                    b.HasIndex("Url");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("QInfoRanker.Core.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Term");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("QInfoRanker.Core.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AuthorityWeight")
                        .HasColumnType("REAL");

                    b.Property<bool>("HasNativeScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchUrlTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorityWeight = 0.69999999999999996,
                            HasNativeScore = true,
                            IsActive = true,
                            IsAutoDiscovered = false,
                            Name = "はてなブックマーク",
                            SearchUrlTemplate = "https://b.hatena.ne.jp/search/tag?q={keyword}",
                            Type = "Scraping",
                            Url = "https://b.hatena.ne.jp/"
                        },
                        new
                        {
                            Id = 2,
                            AuthorityWeight = 0.69999999999999996,
                            HasNativeScore = true,
                            IsActive = true,
                            IsAutoDiscovered = false,
                            Name = "Qiita",
                            SearchUrlTemplate = "https://qiita.com/tags/{keyword}",
                            Type = "API",
                            Url = "https://qiita.com/"
                        },
                        new
                        {
                            Id = 3,
                            AuthorityWeight = 0.69999999999999996,
                            HasNativeScore = true,
                            IsActive = true,
                            IsAutoDiscovered = false,
                            Name = "Zenn",
                            SearchUrlTemplate = "https://zenn.dev/search?q={keyword}",
                            Type = "Scraping",
                            Url = "https://zenn.dev/"
                        },
                        new
                        {
                            Id = 4,
                            AuthorityWeight = 0.90000000000000002,
                            HasNativeScore = false,
                            IsActive = true,
                            IsAutoDiscovered = false,
                            Name = "arXiv",
                            SearchUrlTemplate = "https://export.arxiv.org/api/query?search_query={keyword}",
                            Type = "API",
                            Url = "https://export.arxiv.org/"
                        },
                        new
                        {
                            Id = 5,
                            AuthorityWeight = 0.80000000000000004,
                            HasNativeScore = true,
                            IsActive = true,
                            IsAutoDiscovered = false,
                            Name = "Hacker News",
                            SearchUrlTemplate = "https://hn.algolia.com/api/v1/search?query={keyword}",
                            Type = "API",
                            Url = "https://news.ycombinator.com/"
                        },
                        new
                        {
                            Id = 6,
                            AuthorityWeight = 0.59999999999999998,
                            HasNativeScore = true,
                            IsActive = true,
                            IsAutoDiscovered = false,
                            Name = "Reddit",
                            SearchUrlTemplate = "https://www.reddit.com/search/?q={keyword}",
                            Type = "Scraping",
                            Url = "https://www.reddit.com/"
                        });
                });

            modelBuilder.Entity("QInfoRanker.Core.Entities.Article", b =>
                {
                    b.HasOne("QInfoRanker.Core.Entities.Source", "Source")
                        .WithMany("Articles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("QInfoRanker.Core.Entities.Source", b =>
                {
                    b.HasOne("QInfoRanker.Core.Entities.Keyword", "Keyword")
                        .WithMany("Sources")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("QInfoRanker.Core.Entities.Keyword", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("QInfoRanker.Core.Entities.Source", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
